# Generated by Django 4.0 on 2023-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='channel_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
