# Generated by Django 4.0 on 2023-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_channel_name_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='day',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='order_num',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
